### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by davru** [DSGDSR/shar3#1]
- [ ] limit to 2 public share per day
- [x] loader limit and reload
- [ ] when installing make a tour
- [ ] test updater
- [x] test long loader reload
- [ ] alert close, color and center
- [ ] copy image failing
- [ ] stop sharing circle
- [ ] switch change tooltip from private to tooltip
- [ ] remove language flags

https://github.com/tauri-apps/tauri/issues/4669#issuecomment-1242816074
